# SwiftLint Configuration for AFHAM
# BrainSAIT Healthcare AI Platform

# Paths to include
included:
  - AFHAM/

# Paths to exclude
excluded:
  - AFHAM/Resources
  - build
  - derived_data
  - .build
  - Pods

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - line_length

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - URL
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - T
    - U
    - V

# File header
file_header:
  required_pattern: |
                    \/\/
                    \/\/ AFHAM \- BrainSAIT Healthcare AI Platform
                    \/\/ Copyright © \d{4} BrainSAIT Ltd\. All rights reserved\.
                    \/\/

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_unwrap:
    name: "No Force Unwrapping"
    regex: '!\s*[^=]'
    message: "Avoid force unwrapping, use optional binding instead"
    severity: error

  no_direct_api_keys:
    name: "No Hardcoded API Keys"
    regex: 'API[_-]?KEY|api[_-]?key|token|password'
    message: "Don't hardcode API keys or sensitive data"
    severity: error

  pdpl_comment:
    name: "PDPL Compliance Comment"
    regex: '(encrypt|decrypt|userdata|personal|sensitive)'
    message: "Ensure PDPL compliance for data handling"
    severity: warning

# Reporter type
reporter: "xcode"
